# Generated by Django 4.2.2 on 2023-08-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_question_downvotes_question_upvotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-posted_on']},
        ),
    ]
