# Generated by Django 4.2.2 on 2023-08-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_answer_downvotes_answer_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
    ]
